### ISSUE TITLE
tooltips for navigation

### ISSUE THREAD

**Issue by FlorianZipser** [korpling/pepperModules-SaltInfoModules#11]
When document or corpus names are too long to be displayed in navigation, just show displayable text and cut the rest of. Also generate tooltips showing the complete names.

**Comment by VivianV** [comment]
![ridges_herbology_version4 1 - mozilla firefox_001](https://cloud.githubusercontent.com/assets/8623959/6804384/a20f756a-d23d-11e4-99d0-107c84cc84a9.png)

**Comment by VivianV** [comment]
done
