### ISSUE TITLE
missing ',' in salt-project

### ISSUE THREAD

**Issue by FlorianZipser** [korpling/pepperModules-SaltInfoModules#15]
In Json part of salt-project file a ',' is missing after XSLT conversion:

         "text" : "CvO_10_SEL_de_we_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/en/CvO_10_SEL_de_we_katk.html" }
         } { 
         "text" : "CvO_10_SEL_de_wn_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/en/CvO_10_SEL_de_wn_katk.html" }
         }, {

**Comment by FlorianZipser** [comment]
Unfortunatly it is not possible to upload files to issues. Therefore here is the complete json from salt-project:

 $(function() {
         $('#jstree2').jstree(
         { 
         'core' : { 'data' : 
         [
          { 
         "text" : "exmaralda",
         "metadata" : { "href" : ".exmaralda.html" },
         "state" : { "opened" : true }, icon : "fa fa-folder-o", 
         "children" : [ 
          { 
         "text" : "de",
         "metadata" : { "href" : ".exmaralda/de.html" },
         icon : "fa fa-folder-o", 
         "children" : 
         [  { 
         "text" : "CvO_12_SUA_de_we_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/de/CvO_12_SUA_de_we_katk.html" }
         }, { 
         "text" : "CvO_7_ALP_de_we_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/de/CvO_7_ALP_de_we_katk.html" }
         }, { 
         "text" : "CvO_7_ALP_de_wn_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/de/CvO_7_ALP_de_wn_katk.html" }
         } 
         ] 
          }, { 
         "text" : "en",
         "metadata" : { "href" : ".exmaralda/en.html" },
         icon : "fa fa-folder-o", 
         "children" : 
         [  { 
         "text" : "CvO_10_SEL_de_we_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/en/CvO_10_SEL_de_we_katk.html" }
         } { 
         "text" : "CvO_10_SEL_de_wn_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/en/CvO_10_SEL_de_wn_katk.html" }
         }, { 
         "text" : "KTS_5_ELA_de_we_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/en/KTS_5_ELA_de_we_katk.html" }
         }, { 
         "text" : "KTS_5_ELA_de_wn_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/en/KTS_5_ELA_de_wn_katk.html" }
         }, 
         ] 
          }, { 
         "text" : "tr",
         "metadata" : { "href" : ".exmaralda/tr.html" },
         icon : "fa fa-folder-o", 
         "children" : 
         [  { 
         "text" : "CvO_10_EDA_de_we_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/tr/CvO_10_EDA_de_we_katk.html" }
         }, { 
         "text" : "CvO_10_EDA_de_wn_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/tr/CvO_10_EDA_de_wn_katk.html" }
         }, { 
         "text" : "KTS_5_REY_de_we_katk", 
         icon : "fa fa-file-o", 
         "metadata" : { "href" : ".exmaralda/tr/KTS_5_REY_de_we_katk.html" }
         } 
         ] 
          }] 
         }
         ]
         }
         }).bind( "select_node.jstree", function(e,
         data) { var href = data.instance.get_node(data.selected[0]).original.metadata.href
         $('#content').load(href); }) });

**Comment by VivianV** [comment]
The ',' was missing, because the preceding document was previously the last document, after alphaltical sorting, the comma was already deleted.

**Comment by VivianV** [comment]
solved with string comparison.
