### ISSUE TITLE
text for "Annotation" section

### ISSUE THREAD

**Issue by FlorianZipser** [korpling/pepperModules-SaltInfoModules#20]
Is it possible to have two different description texts for "Annotation" section? 
1. In case of there are no layers at all:
"This section contains all annotations contained in this document or corpus. Annotations in Salt are attribute-value-pairs. This table contains the frequencies of all annotation names and annotation values."
2. In case, there are further layers:
This section contains all annotations contained in this document or corpus which does not belong to any layer. Annotations being contained in layers are visualized below. Annotations in Salt are attribute-value-pairs. This table contains the frequencies of all annotation names and annotation values.

**Comment by VivianV** [comment]
done
