### ISSUE TITLE
json-file funzt nicht, wenn slayer-array gelöscht wird

### ISSUE THREAD

**Issue by VivianV** [korpling/pepperModules-SaltInfoModules#28]
no text

**Comment by VivianV** [comment]
anbei sächsische weltchronik noch mal ohne leerzeichen-files. nu geht 
die konvertierung leider gar nicht mehr :/

Am 20.04.2015 um 16:23 schrieb Florian Zipser:

**Comment by FlorianZipser** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Fehlte hier ein Anhang?

Am 20.04.2015 um 21:49 schrieb VivianV:
> anbei sächsische weltchronik noch mal ohne leerzeichen-files. nu
> geht die konvertierung leider gar nicht mehr :/
> 
> Am 20.04.2015 um 16:23 schrieb Florian Zipser:
>> 
>> Closed #28 
>> <https://github.com/korpling/pepperModules-SaltInfoModules/issues/28>
>>  via e6824b6 
>> <https://github.com/korpling/pepperModules-SaltInfoModules/commit/e68
24b6168025f4b1e1ad6dc1a1f4fdd72936519>.
>>
>>
>> 
—
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/korpling/pepperModules-SaltInfoModules/issues/28#
event-285251807>.
>>
>
>> 
> 
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/korpling/pepperModules-SaltInfoModules/issues/28#is
suecomment-94551996
>
> 
- -- 
Florian Zipser
Dipl. Inf.
Institute for German Language and Linguistics
Humboldt-Universität zu Berlin
Unter den Linden 6
D-10099 Berlin

phone: +49 (0)30 2093 9720
mail:  f.zipser@gmx.de
web:   http://u.hu-berlin.de/zipser
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBAgAGBQJVNpB/AAoJEPzXRiHkLJBh07gH/A3+6p6yP3+vEesv9cE69qge
SxMPhdQrdZb9suYOrxihgy8fP8IoE61W4ie//igo7TljsOoQHAoCXaDL8LA3Pg/R
VQAAdh/3jpszHHvvwrpdCvqPR8XsCEdBehU7kDsQWA9mW5JI/R7pHFd4EBMu3Q+h
D8IO8vns8EJV4vaPZxOX5fYbRWuXWhtYtpdfcytQP4iQ5MX4G2yfxCxBu+o/TbZ0
sMO/iW8o1HmvYTPs6vFL4iz+ygjzx2bpH7QtsIK2onMPXAL2r5m/EFFZmKFMa1Z9
L8SId3zzaltsku7djvCoLbdIsrJWIgo/PTaX4NR2AIn2dI4sxhG52ngAK9Ug3dE=
=C9qj
-----END PGP SIGNATURE-----
